apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      cni.projectcalico.org/containerID: 3ded32e0388ed052ebe86d919a07985e477438260bfe8907a11b4b684ffe2556
      cni.projectcalico.org/podIP: 192.168.102.159/32
      cni.projectcalico.org/podIPs: 192.168.102.159/32
    creationTimestamp: "2023-02-06T13:26:11Z"
    generateName: nginx-nano-pod-enabled-869c5bd95b-
    labels:
      app: nginx-nano-pod-enabled
      nano-pods: my-nano-pod
      pod-template-hash: 869c5bd95b
    name: nginx-nano-pod-enabled-869c5bd95b-6nkct
    namespace: nano-pod-test
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: nginx-nano-pod-enabled-869c5bd95b
      uid: deeabcb3-3dd1-4bdd-bcf4-220ceeac72ac
    resourceVersion: "47505678"
    uid: 65995871-3f30-46d0-9d95-51d0df7c19bb
  spec:
    containers:
    - env:
      - name: env0101
        value: value0103
      - name: env0102
        value: value0103
      - name: MYSQL_ALLOW_EMPTY_PASSWORD
        value: "true"
      - name: MYSQL_DATABASE
        value: mydb
      image: treezh-docker.pkg.coding.net/demo03/public/mysql:8.0.31
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        initialDelaySeconds: 15
        periodSeconds: 20
        successThreshold: 1
        tcpSocket:
          port: 3306
        timeoutSeconds: 1
      name: mysql01
      readinessProbe:
        failureThreshold: 3
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        tcpSocket:
          port: 3306
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-557gm
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: "63"
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-557gm
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2023-02-06T13:26:11Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2023-02-06T13:26:31Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2023-02-06T13:26:31Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2023-02-06T13:26:11Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://01bdf72be38da5cf2956f2b6d959ea1ba5d0b61b6f48f9ffcc843477ddbe5f6d
      image: treezh-docker.pkg.coding.net/demo03/public/mysql:8.0.31
      imageID: docker-pullable://treezh-docker.pkg.coding.net/demo03/public/mysql@sha256:cfddf275c8b1ae1583c0f6afb4899d4dbe14111a6462699559a1f4dc8f4d5f6e
      lastState: {}
      name: mysql01
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2023-02-06T13:26:12Z"
    hostIP: 9.135.5.63
    phase: Running
    podIP: 192.168.102.159
    podIPs:
    - ip: 192.168.102.159
    qosClass: Burstable
    startTime: "2023-02-06T13:26:11Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
