apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: nano-pod-webhook-service
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/name: nano-pod-operator
    control-plane: controller-manager
status:
  loadBalancer: {}
