# permissions for end users to edit nanopatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nanopatcher-editor-role
rules:
- apiGroups:
  - nanopod.nanopod.treezh.cn
  resources:
  - nanopatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nanopod.nanopod.treezh.cn
  resources:
  - nanopatchers/status
  verbs:
  - get
