# permissions for end users to view nanopods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nanopod-viewer-role
rules:
- apiGroups:
  - nanopod.nanopod.treezh.cn
  resources:
  - nanopods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nanopod.nanopod.treezh.cn
  resources:
  - nanopods/status
  verbs:
  - get
