# permissions for end users to view nanopatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nanopatcher-viewer-role
rules:
- apiGroups:
  - nanopod.nanopod.treezh.cn
  resources:
  - nanopatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nanopod.nanopod.treezh.cn
  resources:
  - nanopatchers/status
  verbs:
  - get
