# permissions for end users to edit nanoonepatches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nanoonepatch-editor-role
rules:
- apiGroups:
  - nanopod.nanopod.treezh.cn
  resources:
  - nanoonepatches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nanopod.nanopod.treezh.cn
  resources:
  - nanoonepatches/status
  verbs:
  - get
