apiVersion: nanopod.nanopod.treezh.cn/v1
kind: NanoPod
metadata:
  name: default
  namespace: nanopod-test
spec:
  template:
    metadata:
      annotations:
        nanopod/test: "enabled-case"
      labels:
        nanopod-test: "enabled-case"
    spec:
      containers:
        - name: nginx
          env:
            - name: "defaultEnv1"
              value: "enabled-case"
      terminationGracePeriodSeconds: 10